const prompts = [
  'Heads Up',
  'Let Her Rip',
  'Right Out of the Gate',
  'Two Down, One to Go',
  'Not the Sharpest Tool in the Shed',
  "Don't Count Your Chickens Before They Hatch",
  'A Little Bird Told Me',
  'A Lemon',
  'A Cold Fish',
  'Down For The Count',
  'Like Father Like Son',
  'A Dog in the Manger',
  'Keep Your Shirt On',
  'Wake Up Call',
  'A Fool and His Money Are Soon Parted',
  'A Day Late and a Dollar Short',
  'Keep Your Eyes Peeled',
  'Man of Few Words',
  'Wild Goose Chase',
  'Under Your Nose',
  'Drawing a Blank',
  'On Cloud Nine',
  'Hit Below The Belt',
  'Foaming At The Mouth',
  'Dropping Like Flies',
  'Rightful Page',
  'Leaf',
  'Cat',
  'Rose',
  'Eggs',
  'Statue',
  'Fairy',
  'Baby',
  'Strawberry',
  'Slug',
  'Record Player',
  'Moon',
  'Lollipop',
  'Pot of gold',
  'Carousel',
  'Mountain',
  'Feather',
  'Atom',
  'Snowflake',
  'Goldfish',
  'Tiger',
  'Skull',
  'Baseball',
  'Bus',
  'Miniature uncle',
  'Amusing song',
  'Rambunctious insect',
  'Boorish dealer',
  'Half employment',
  'Observant professor',
  'Confident ',
  'Silly opinion',
  'Educated user',
  'Panicky ',
  'Typical beer',
  'Exotic pizza',
  'Hot grandmother',
  'Chicken',
  'Owl',
  'Dinosaur',
  'Pig',
  'Elephant',
  'Airplane',
  'Doll',
];
