include: package:very_good_analysis/analysis_options.2.4.0.yaml
analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
linter:
  rules:
    public_member_api_docs: false
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
    require_trailing_commas: false
    avoid_redundant_argument_values: false
    prefer_int_literals: false
    avoid_web_libraries_in_flutter: false
