name: io_photobooth
description: I/O Photo Booth app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.3.0-1.0.pre.227

dependencies:
  analytics:
    path: packages/analytics
  authentication_repository:
    path: packages/authentication_repository
  bloc: 7.2.1
  camera:
    path: packages/camera/camera
  cloud_firestore: 3.1.4
  cross_file: 0.3.2
  equatable: 2.0.3
  firebase_auth: 1.4.1
  firebase_core: 1.10.5
  firebase_storage: 8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: 7.3.3
  flutter_localizations:
    sdk: flutter
  go_router: ^2.5.2
  image_compositor:
    path: packages/image_compositor
  intl: 0.17.0
  just_audio: 0.7.5
  photobooth_ui:
    path: packages/photobooth_ui
  photos_repository:
    path: packages/photos_repository
  rxdart: 0.26.0
  session_repository:
    path: packages/session_repository
  staggered_grid_view_flutter: 0.0.4
  uuid: 3.0.5
  very_good_analysis: 2.4.0

dev_dependencies:
  bloc_test: 8.3.0
  flutter_test:
    sdk: flutter
  mocktail: 0.1.4
  mocktail_image_network: 0.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/
    - assets/backgrounds/
    - assets/images/
    - assets/icons/
    - assets/props/google/
    - assets/props/hats/
    - assets/props/eyewear/
    - assets/props/food/
    - assets/props/shapes/
