name: authentication_repository
description: Repository which manages user authentication using Firebase Authentication.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: 2.0.3
  firebase_auth: 1.4.1
  firebase_core: 1.10.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.1.4
  very_good_analysis: 2.4.0
