name: photos_repository
description: repository that manages the photo domain
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_core: ^1.10.5
  firebase_storage: ^8.1.3
  flutter:
    sdk: flutter
  image_compositor:
    path: ../image_compositor

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  very_good_analysis: ^2.4.0
