name: session_repository
description: repository that manages the sessions
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: 3.1.4
  equatable: 2.0.3
  firebase_core: 1.10.5
  firebase_storage: 8.1.3
  flutter:
    sdk: flutter
  json_annotation: 4.4.0

dev_dependencies:
  build_runner: 2.1.5
  flutter_test:
    sdk: flutter
  json_serializable: 6.1.1
  mocktail: 0.1.4
  very_good_analysis: 2.4.0
